- conftest.py
It may differ from the compiled mender version.
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Use dedicated mender_deb_version fixture for deb package.

- .gitlab-ci.yml
As it is done in the rest of the pipelines for now...
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
> Disable publishing the Docker image in Docker Hub

- docker/docker-files-raspbian/prepare-raspbian-img.sh
Change ported (and amended) from #7 
```
commit fe169c75e9f8d5e1127fb9d487f9610b77cceda7
Author: Manuel Zedel <manuel.zedel@northern.tech>
Date:   Tue Aug 27 11:40:46 2019 +0200
switched to wget to download raspbian due to curl security
this is necessary as raspberrypi.org seems to use a too short tls key,
which is not tolerable for curl but for wget
commit 208718f1a5a2d684663ba79fba636f9e90fcb03a
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Wed Aug 28 11:09:39 2019 +0200
Add --no-clobber option to wget downloads
So that we don't make copies of the downloaded raspbian files
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
```
> Switch curl wget downloads

- conftest.py
- helpers.py
```
commit 511c4e9f32899344e19c7ed813a45dae267f5135
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Thu Sep 5 15:28:17 2019 +0200
Implement alternative 'run' method using system's ssh
For where we cannot use Fabric, same as above 'put' method
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
commit 3edec1e9022c46057ac6b60ccc741eace875411a
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Mon Sep 9 11:16:32 2019 +0200
Add some debug level logging to helpers and fixtures
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
```
> Minor improvements while working on MEN-2599

- conftest.py
This speeds up local testing dramatically. Whether it speeds up Gitlab
depends on runner setup.
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Make privileged client container.

- .gitlab-ci.yml
- conftest.py
- container_props.py
- helpers.py
- pyproject.toml
-  [Python black] Enable style enforcement and update files
- MEN-3601: Install Mender deb package missing dependencies in fixture
This should fix integration tests at mender-binary-delta repo.
Follow-up from https://github.com/mendersoftware/mender-dist-packages/pull/30
> MEN-3601: Install Mender deb package missing dependencies in fixture

- helpers.py
The Yocto builds from zeus have a lot of trailing log messages after
the kernel prompt, so we need to check a larger tail to catch the
login string.
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Work around log garbage at the login prompt.

- conftest.py
existing fixtures allow creating a test container per test class.
this means one container, and its complete state, is shared across
all functions in a test class.
this is ok-ish if that's the idea - test funcs must be ordered in a
way that respects modifications made in previous funcs. this can get
out of control quickly if new funcs are added to a class.
a more convenient pattern is to have the container created per test
func - this way each scenario starts with a clean slate, so:
extend the set of fixtures with their function-scoped versions.
Issues: 4150
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> conftest: func-scoped versions of existing fixtures

- mender-client-acceptance-testing/Dockerfile
Needed for testing in Yocto warrior branch, which we still need to
maintain.
> [mender-client-acceptance-testing] Add Python2 requirements

- conftest.py
Plus update the download URL and add a note on the expected fixture.
> setup_mender_configured: Verify mender-client is actually installed

- backend-acceptance-testing/requirements-py3.txt
the bravado upgrade is problematic as it breaks the
library API - and existing acceptance tests (for sure
in deviceauth, possibly everywhere).
the upgrade was from 9.x.x to 11.x.x so that's expected.
however, trying to revert to 9.3.2 (highest 9.x.x version) still
results in the same problems.
we must revert to 9.2.2 to make them go away.
just to be safe, do the same with the minio upgrade.
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> python-requirements: revert 'major' dependabot upgrades

- helpers.py
Following changes from integration test framework. See:
* https://github.com/mendersoftware/integration/pull/1333
* https://github.com/mendersoftware/integration/pull/1336
> paramiko: set look_for_keys and allow_agent to False

- .gitlab-ci.yml
For some reason the base image used to include the tool but not anymore.
> Pipeline fix: install fdisk in build_prep

- backend-acceptance-testing/Dockerfile.backend-tests
- backend-acceptance-testing/requirements-py3.txt
Required for acceptance tests CLI coverage.
> Add docker to backend acceptance test image python requirements

- .gitlab-ci.yml
- README.md
pipeline: upload/fetch guiE2eTestingImage from S3 temp space
This image is now too big for GitLab CI artifacts. Use our own method to
save big artifacts in the S3 temporary space.
Update also qaTestingImage handling to use the new helpers (and security
mechanism).
Bonus:
* README: fix typo and table formatting
> pipeline: upload/fetch guiE2eTestingImage from S3 temp space + README: fix typo and table formatting

- .gitlab-ci.yml
The CI runner is running out of space when loading gui testing image -
remove previous images to free up space.
> pipeline: publish: remove images to save space

- backend-acceptance-testing/requirements-py3.txt
chore(redo): Add redo dependency to allow retries in backend test containers
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> chore(redo): Add redo dependency to allow retries in backend test containers

- backend-integration-testing/Dockerfile
> chore: pinned kubectl as newer versions might not work with aws iam

- backend-acceptance-testing/requirements-py3.txt
chore(semver): Add semver dependency to use in backend acceptance tests
Ticket: MEN-5667
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> chore(semver): Add semver dependency to use in backend acceptance tests

- helpers.py
New versions of the scp program uses the SFTP protocol by
default. However SFTP is not installed in our qemu hosts, and hence
this does not work.
The fix is simple. Fall back to the legacy functionality. The SCP
protocol, though aged, works just fine for our needs.
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> ci(scp): Fall back to the legacy SCP protocol

- .gitlab-ci.yml
Ubuntu Bionic standard LTS support is EOL.
> QA-600: chore: Deprecate Ubuntu Bionic debian packages

- .gitlab-ci.yml
Merging `build_prep` and `build` stages and reordering to more standard CI stages build, test, publish.
> ci: Switch to `needs` and simplify stages

- container_props.py
The `docker.io/mendersoftware/mender-test-containers` images have long been deprecated in favor of `registry.gitlab.com`.
> test: Update reference for base image

- .gitlab-ci.yml
The comment already explains why, the keyword was changed unintentionally after the comment was added.
Ticket: QA-655
> build: Revert from `needs` back to `dependencies` for publication.

- backend-integration-testing/Dockerfile
The old one was deprecated back in 2023 and stopped working; install the kubectl version 1.29 using the current official APT repo.
Ticket: None
> chore: switch to the newer APT repo for Kubernetes

- .gitlab-ci.yml
It seems like `rules:manual` is not treated the same was as top-level `manual`. In the former, the pipeline expects the job to be run at some point (hence in never finishes) while the latter is treated as an optional job.
Refactor the pipeline code to accommodate for this.
> ci: Fix "blocked" pipelines by refactoring the manual job

- backend-integration-testing/requirements-py3.txt
- helpers.py
Follow up from QA-650 where we removed Fabric dependency in the integration repo. This allows mender-configure-module to be updated, since it doesn't have Fabric, and it uses this repo as a submodule.
Ticket: QA-666
> chore: remove fabric dependency

- backend-acceptance-testing/requirements-py3.txt
The deployments acceptance tests are the boto3 (S3 API) client instead of relying on the vendor specific `minio` dependency.
> test(backend-acceptance): Add boto3 to Python requirements

- backend-acceptance-testing/requirements-py3.txt
requests 2.32.0 breaks docker.
> chore: Roll back requests to 2.31.0

- .gitlab-ci.yml
- conftest.py
- container_props.py
- docker/docker-files-raspbian/Dockerfile
- docker/docker-files-raspbian/prepare-raspbian-img.sh
- helpers.py
In the context of deprecating Debian Buster, we need to bump the tester
image to the oldest still supported release.
At the time of Bullseye release, the upstream project renamed the OS
from "Raspbian" to "Raspberry Pi OS" (`raspios` for short) so let's stick
to that for our naming of the image and the internal variables. For the
Docker image name, remove the "latest" part as it is not meaningful.
The rest of the changes [I hope that] are self-explanatory.
> QA-691: Upgrade Raspberry Pi OS tester image for Bullseye release

- helpers.py
`failed` returns True if the program exited with
a nonzero return code, and False otherwise.
Ticket: QA-666
> chore: added `failed` instance variable to Result

- .gitlab-ci.yml
Because of this error:
mount: img-boot: mount failed: Operation not permitted.
Ticket: None
> ci: revert to gcp runner

- .gitlab-ci.yml
- mender-dist-packages-building/Dockerfile
This distribution has migrated to deb822 format for the APT sources
file, so modify the script accordingly. See comment in the code.
> MEN-7242: Add new builder image for dist packages: Ubuntu Noble

- .gitlab-ci.yml
Currently the master branch of Copybara is broken, and to prevent failure we just revert to the previous commit. Here's the issue opened: https://github.com/google/copybara/issues/299
Ticket: QA-678
> ci: workaround upstream build issue

- .gitlab-ci.yml
The Copybara team fixed the upstream build process. We can now build the master branch again
https://github.com/google/copybara/commit/d28b4fbf7fcb4dd5a989b3ca7946307a32aea157
> ci: restore copybara master

- .github/dependabot.yml
The build (and test) of the images will be removed a bit later, but disable the dependabot configuration already to remove confusion and noise internally in the team.
> QA-735: Disable dependabot for backend testing images

- gui-e2e-testing/Dockerfile
The upstream artifact name has changed, so the previous one was not anymore in the repository
Ticket: QA-805
> ci: fix mender-artifact version

- .gitlab-ci.yml
- mender-dist-packages-building/Dockerfile
- mender-dist-packages-building/build.sh
Important: this commit modifies the name of the builder images.
The purpose is to better show what the image is meant to (simulated build or cross compiling build) and, most importantly, not reuse the old Debian armhf (what was really Raspberry Pi OS armhf) with the new Debian armhf (the "good" one).
The actual changes are minimal: remove the special handling of the Dockerfile for Debian armhf and add some extra checks in the wrapper to make sure we don't build unexpected images.
> MEN-7731: Add mender-dist-packages builder image for Debian armhf

- helpers.py
We started to see random failures in mender-dist-packages acceptance tests on this wait for boot. This test suite run arm containers on x86 through emulation.
While in the past 3 minutes showed to be enough, it seems like some either in the image or in the infra made the tests run into this limit.
> QA-929: Increase timeout waiting for container to 15 minutes

- conftest.py
- container_props.py
- helpers.py
Developed together with https://github.com/mendersoftware/mender-dist-packages/pull/537. And proven to be working by [its pipeline](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/1943849242).
> Fixes for running tests locally and on a different architecture than armhf

- container_props.py
The container is no longer available, it was removed in 5b6c0a7022aca8e51173ff65dffea437f18f2ca7.
Ticket: QA-1086
Changelog: none
> chore: Drop MenderTestRaspbian container spec
