mendersoftware/mender-test-containers

- docker/docker-files-raspbian/prepare-raspbian-img.sh
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
> Fix prepare-raspbian-img.sh to work on Docker containers

- .gitlab-ci.yml
- container_props.py
> enabled docker image publishing to gitlab registry in ci

- .gitlab-ci.yml
- conftest.py
For mender client 2.2.x, the deb package includes an interactive post
install script. Force it to be unattended.
> Update fixture to use an unattended install of the deb package

- .gitlab-ci.yml
- backend-acceptance-testing/Dockerfile.backend-tests
- backend-acceptance-testing/requirements-py3.txt
this is to be shared between all the acceptance tests
@alfrunes this is what I meant in https://github.com/mendersoftware/deviceauth/pull/408 :)
> added backend test image + publishing

- backend-acceptance-testing/requirements-py3.txt
as seen missing in https://gitlab.com/Northern.tech/Mender/workflows-enterprise/-/pipelines/214657849 
> backend testing: added redis support to allow usage in workflows enterprise

- backend-acceptance-testing/requirements-py3.txt
Now that we have [QA-261](https://tracker.mender.io/browse/QA-261) in place, bringing together #19, #24, #42, #45, #47, #50.
> Dependabot backend acceptance

- .gitignore
- .gitlab-ci.yml
- docker/docker-build-raspbian
- docker/docker-files-raspbian/Dockerfile
- docker/docker-files-raspbian/prepare-raspbian-img.sh
Changelog: title
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
> Update raspian image to Buster (2019-07-12)

- backend-acceptance-testing/requirements-py3.txt
> dependabot: backend acceptance testing

- .github/dependabot.yml
- .gitlab-ci.yml
- README.md
- gui-e2e-testing/Dockerfile
> added gui e2e test image + publishing

- gui-e2e-testing/Dockerfile
> chore: remove currently unused tools from gui image

- .gitlab-ci.yml
> pipeline: publish: Fix typo

- mender-client-acceptance-testing/Dockerfile
> fix(client-acceptance): fixed docker installation

- gui-e2e-testing/Dockerfile
> fix(gui-e2e-testing): fixed faulty demo-artifact download

- backend-acceptance-testing/requirements-py3.txt
chore(k8s-support): Add kubernetes dependency
Ticket: QA-406
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> chore(k8s-support): Add kubernetes dependency

- helpers.py
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
> chore: bind to IPv4 only when doing port-forwarding

- .gitlab-ci.yml
> ci: made image builds use buildkit

- backend-integration-testing/requirements-py3.txt
Ticket: QA-469
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> test: backend integration tests websockets requirement

- mender-client-acceptance-testing/Dockerfile
> fix: workaround for gke kernel suffix

- backend-acceptance-testing/requirements-py3.txt
https://github.com/docker/docker-py/issues/3113
> fix: Pin urllib3 < 2 because of Docker client incompatibility

- .github/dependabot.yml
- .gitlab-ci.yml
- README.md
- aws-k8s-toolbox/Dockerfile
* Using Gitlab registry as a container storage
* Added aws k8s image toolbox creation for helm pipelines
> Using Gitlab registry as a container storage

- .gitlab-ci.yml
> fix: correct variable name for the gui-e2e-testing

- .gitlab-ci.yml
- mender-dist-packages-building/Dockerfile
- mender-dist-packages-building/README.md
- mender-dist-packages-building/install-armv6-cross-toolchain
Goes along with:
https://github.com/mendersoftware/mender-dist-packages/pull/333
> Add support for the armv6 cross-compiler-suite from bootlin

- .gitlab-ci.yml
- docker-multiplatform-buildx/Dockerfile
Needed to build Alvaldi containers
Ticket: ALV-27
> feat: added docker buildx multiplatform image

- .gitlab-ci.yml
> Fix: multiplatform base image push

- aws-k8s-toolbox/Dockerfile
Needed to Helm version bump: https://northerntech.atlassian.net/browse/ALV-47
> feat: added yq package

- aws-k8s-toolbox/Dockerfile
To allow resolving Load Balancer address for internal testing
> Added dnsutils to helm ci tests

- mender-dist-packages-building/Dockerfile
- mender-dist-packages-building/install-armv6-cross-toolchain
Re-enable building of Golang packages with our new cross-compiler setup.
Ticket: MEN-6759
Changelog: Title
> fix: Support building golang packages again

- .gitlab-ci.yml
- README.md
- goveralls/Dockerfile
> Goveralls base image

- .gitlab-ci.yml
> Moving to kubeconform 0.6.3 in the pipeline

- .gitlab-ci.yml
- README.md
- mongodb-backup-runner/Dockerfile
The job requires usage of azure-cli, which
is not in the Debian repositories
Ticket: MC-7038
> Custom runner for mongodb dr backups

- backend-integration-testing/requirements-py3.txt
> chore: added aiosmtpd to requirements-py3.txt

- .gitlab-ci.yml
using PoC by @lluiscampos 
Three friends:
* https://github.com/mendersoftware/mender-qa/pull/723
* https://github.com/mendersoftware/mendertesting/pull/315
* https://github.com/mendersoftware/mender-test-containers/pull/495
Changelog: Title
Ticket: QA-505
> feat: trigger backend repos pipelines.

- helpers.py
Put is used by some tests, therefore added a wrapper around the put function in the Connection class, as we have removed the Fabric dependency.
> Remove fabric dependency 

- .gitlab-ci.yml
- terragrunt-trivy-toolbox/Dockerfile
With this image, a terragrunt and trivy test is run.
Also moved to hetnzer build host, and to Gitlab Dependency Proxy images.
> Toolbox image for MMS CI security

- gui-e2e-testing/Dockerfile
> feat: enabled mender-artifact usage during gui tests

- .gitlab-ci.yml
Added docker logins to prevent docker pull rate limit issue
Ticket: QA-730
> Hetzner rate limit

- .gitlab-ci.yml
Added Copybara container image to be used in other CICD pipelines to sync repositories
Ticket: QA-678
> ci: add copybara image

- .gitlab-ci.yml
- README.md
- release-please/Dockerfile
> ci: added release-please base image

- .gitlab-ci.yml
This reverts commit 123b9a3afb9bf6f2b379afb5f78985ed5b0d7723.
> revert: ci: add copybara image

- .gitlab-ci.yml
Fixes runc errors in the hetzner runner
Ticket: QA-823
> ci: pin docker to v27.3

- conftest.py
`uname -m` reports *machine hardware name* which, when running a "compatible" image (like ARMv7 on ARMv8 or i386 on x86_64) doesn't reflect the OS/image architecture. Fortunately, `$MACHTYPE` provided by Bash reflects what the running Bash was built for which tells us the architecture/machine type of the OS/image we are running.
Ticket: QA-1138
Changelog: none
> fix: Improve machine type detection in setup_mender_configured()

- .gitlab-ci.yml
> ci: Add Debian 13 support
